# Generated by Django 5.2.8 on 2025-12-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StressItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('project_name', models.CharField(max_length=200)),
                ('stress_name', models.CharField(max_length=200)),
                ('stress_args', models.CharField(max_length=500)),
                ('label', models.CharField(max_length=150)),
            ],
        ),
    ]
