# Generated by Django 5.2.8 on 2025-12-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('project_name', models.CharField(max_length=200)),
                ('create_time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('stress_id', models.IntegerField()),
                ('stress_status', models.CharField(max_length=150)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('execute_time', models.DateTimeField(blank=True, null=True)),
                ('run_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StressItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stress_name', models.CharField(max_length=200, unique=True)),
                ('stress_command', models.TextField()),
                ('stress_args', models.TextField()),
                ('stress_label', models.TextField()),
                ('stress_summary', models.TextField()),
            ],
        ),
    ]
