# Generated by Django 5.2.8 on 2025-12-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('project_name', models.CharField(max_length=200)),
                ('create_time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('stress_id', models.IntegerField()),
                ('stress_status', models.CharField(max_length=150)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('execute_time', models.DateTimeField(blank=True, null=True)),
                ('run_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='stressitem',
            name='label',
        ),
        migrations.RemoveField(
            model_name='stressitem',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='stressitem',
            name='username',
        ),
        migrations.AddField(
            model_name='stressitem',
            name='stress_command',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stressitem',
            name='stress_label',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stressitem',
            name='stress_summary',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stressitem',
            name='stress_args',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stressitem',
            name='stress_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
